# Generated by Django 3.2.2 on 2021-05-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taskg',
            new_name='Task',
        ),
    ]
